# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: kalitron-furniture-studio
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NjNkYmEzZmI0YjlhNjdiYTJkYjc4ZjNmNTQ4NDM5ZjhjNWMzNjFiNmRjNDg5ODc3M2MyNmNkNDAxMzczZTdkZDY0ZDdmNWU0YTFlYTAyZWYxMmU0OTAzMmFiYmJkNjU0ZjA0MjgwOTZmMjBlZTU2Nzk0MDBlNGJjYmYwZTMyNGM=
