package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CabinetTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetTemplateAllPropertiesEquals(CabinetTemplate expected, CabinetTemplate actual) {
        assertCabinetTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertCabinetTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetTemplateAllUpdatablePropertiesEquals(CabinetTemplate expected, CabinetTemplate actual) {
        assertCabinetTemplateUpdatableFieldsEquals(expected, actual);
        assertCabinetTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetTemplateAutoGeneratedPropertiesEquals(CabinetTemplate expected, CabinetTemplate actual) {
        assertThat(actual)
            .as("Verify CabinetTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetTemplateUpdatableFieldsEquals(CabinetTemplate expected, CabinetTemplate actual) {
        assertThat(actual)
            .as("Verify CabinetTemplate relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getDefaultWidthMm()).as("check defaultWidthMm").isEqualTo(expected.getDefaultWidthMm()))
            .satisfies(a -> assertThat(a.getDefaultHeightMm()).as("check defaultHeightMm").isEqualTo(expected.getDefaultHeightMm()))
            .satisfies(a -> assertThat(a.getDefaultDepthMm()).as("check defaultDepthMm").isEqualTo(expected.getDefaultDepthMm()))
            .satisfies(a -> assertThat(a.getMinWidthMm()).as("check minWidthMm").isEqualTo(expected.getMinWidthMm()))
            .satisfies(a -> assertThat(a.getMaxWidthMm()).as("check maxWidthMm").isEqualTo(expected.getMaxWidthMm()))
            .satisfies(a -> assertThat(a.getSupportsDoors()).as("check supportsDoors").isEqualTo(expected.getSupportsDoors()))
            .satisfies(a -> assertThat(a.getSupportsDrawers()).as("check supportsDrawers").isEqualTo(expected.getSupportsDrawers()))
            .satisfies(a -> assertThat(a.getSupportsShelves()).as("check supportsShelves").isEqualTo(expected.getSupportsShelves()))
            .satisfies(a ->
                assertThat(a.getFusionTemplateName()).as("check fusionTemplateName").isEqualTo(expected.getFusionTemplateName())
            )
            .satisfies(a -> assertThat(a.getCsvProfileJson()).as("check csvProfileJson").isEqualTo(expected.getCsvProfileJson()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetTemplateUpdatableRelationshipsEquals(CabinetTemplate expected, CabinetTemplate actual) {
        // empty method
    }
}
