package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CabinetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetAllPropertiesEquals(Cabinet expected, Cabinet actual) {
        assertCabinetAutoGeneratedPropertiesEquals(expected, actual);
        assertCabinetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetAllUpdatablePropertiesEquals(Cabinet expected, Cabinet actual) {
        assertCabinetUpdatableFieldsEquals(expected, actual);
        assertCabinetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetAutoGeneratedPropertiesEquals(Cabinet expected, Cabinet actual) {
        assertThat(actual)
            .as("Verify Cabinet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetUpdatableFieldsEquals(Cabinet expected, Cabinet actual) {
        assertThat(actual)
            .as("Verify Cabinet relevant properties")
            .satisfies(a -> assertThat(a.getCabinetCode()).as("check cabinetCode").isEqualTo(expected.getCabinetCode()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getWidthMm()).as("check widthMm").isEqualTo(expected.getWidthMm()))
            .satisfies(a -> assertThat(a.getHeightMm()).as("check heightMm").isEqualTo(expected.getHeightMm()))
            .satisfies(a -> assertThat(a.getDepthMm()).as("check depthMm").isEqualTo(expected.getDepthMm()))
            .satisfies(a -> assertThat(a.getDoors()).as("check doors").isEqualTo(expected.getDoors()))
            .satisfies(a -> assertThat(a.getDrawers()).as("check drawers").isEqualTo(expected.getDrawers()))
            .satisfies(a -> assertThat(a.getShelves()).as("check shelves").isEqualTo(expected.getShelves()))
            .satisfies(a -> assertThat(a.getFinish()).as("check finish").isEqualTo(expected.getFinish()))
            .satisfies(a -> assertThat(a.getPositionX()).as("check positionX").isEqualTo(expected.getPositionX()))
            .satisfies(a -> assertThat(a.getPositionY()).as("check positionY").isEqualTo(expected.getPositionY()))
            .satisfies(a -> assertThat(a.getPositionZ()).as("check positionZ").isEqualTo(expected.getPositionZ()))
            .satisfies(a -> assertThat(a.getRotationDeg()).as("check rotationDeg").isEqualTo(expected.getRotationDeg()))
            .satisfies(a -> assertThat(a.getPositionSeq()).as("check positionSeq").isEqualTo(expected.getPositionSeq()))
            .satisfies(a -> assertThat(a.getCsvRowJson()).as("check csvRowJson").isEqualTo(expected.getCsvRowJson()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetUpdatableRelationshipsEquals(Cabinet expected, Cabinet actual) {
        assertThat(actual)
            .as("Verify Cabinet relationships")
            .satisfies(a -> assertThat(a.getTemplate()).as("check template").isEqualTo(expected.getTemplate()))
            .satisfies(a -> assertThat(a.getMaterial()).as("check material").isEqualTo(expected.getMaterial()))
            .satisfies(a -> assertThat(a.getSpec()).as("check spec").isEqualTo(expected.getSpec()));
    }
}
