package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CabinetPartAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetPartAllPropertiesEquals(CabinetPart expected, CabinetPart actual) {
        assertCabinetPartAutoGeneratedPropertiesEquals(expected, actual);
        assertCabinetPartAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetPartAllUpdatablePropertiesEquals(CabinetPart expected, CabinetPart actual) {
        assertCabinetPartUpdatableFieldsEquals(expected, actual);
        assertCabinetPartUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetPartAutoGeneratedPropertiesEquals(CabinetPart expected, CabinetPart actual) {
        assertThat(actual)
            .as("Verify CabinetPart auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetPartUpdatableFieldsEquals(CabinetPart expected, CabinetPart actual) {
        assertThat(actual)
            .as("Verify CabinetPart relevant properties")
            .satisfies(a -> assertThat(a.getPartCode()).as("check partCode").isEqualTo(expected.getPartCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getWidthMm()).as("check widthMm").isEqualTo(expected.getWidthMm()))
            .satisfies(a -> assertThat(a.getHeightMm()).as("check heightMm").isEqualTo(expected.getHeightMm()))
            .satisfies(a -> assertThat(a.getThicknessMm()).as("check thicknessMm").isEqualTo(expected.getThicknessMm()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getEdgeBanding()).as("check edgeBanding").isEqualTo(expected.getEdgeBanding()))
            .satisfies(a -> assertThat(a.getGrainDirection()).as("check grainDirection").isEqualTo(expected.getGrainDirection()))
            .satisfies(a -> assertThat(a.getCncOperation()).as("check cncOperation").isEqualTo(expected.getCncOperation()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCabinetPartUpdatableRelationshipsEquals(CabinetPart expected, CabinetPart actual) {
        assertThat(actual)
            .as("Verify CabinetPart relationships")
            .satisfies(a -> assertThat(a.getMaterial()).as("check material").isEqualTo(expected.getMaterial()))
            .satisfies(a -> assertThat(a.getCabinet()).as("check cabinet").isEqualTo(expected.getCabinet()));
    }
}
