package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CatalogStyleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogStyleAllPropertiesEquals(CatalogStyle expected, CatalogStyle actual) {
        assertCatalogStyleAutoGeneratedPropertiesEquals(expected, actual);
        assertCatalogStyleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogStyleAllUpdatablePropertiesEquals(CatalogStyle expected, CatalogStyle actual) {
        assertCatalogStyleUpdatableFieldsEquals(expected, actual);
        assertCatalogStyleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogStyleAutoGeneratedPropertiesEquals(CatalogStyle expected, CatalogStyle actual) {
        assertThat(actual)
            .as("Verify CatalogStyle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogStyleUpdatableFieldsEquals(CatalogStyle expected, CatalogStyle actual) {
        assertThat(actual)
            .as("Verify CatalogStyle relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getThumbnailPath()).as("check thumbnailPath").isEqualTo(expected.getThumbnailPath()))
            .satisfies(a -> assertThat(a.getStyle()).as("check style").isEqualTo(expected.getStyle()))
            .satisfies(a -> assertThat(a.getPrimaryFinish()).as("check primaryFinish").isEqualTo(expected.getPrimaryFinish()))
            .satisfies(a -> assertThat(a.getPriceRange()).as("check priceRange").isEqualTo(expected.getPriceRange()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogStyleUpdatableRelationshipsEquals(CatalogStyle expected, CatalogStyle actual) {
        // empty method
    }
}
