package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DesignSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignSessionAllPropertiesEquals(DesignSession expected, DesignSession actual) {
        assertDesignSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertDesignSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignSessionAllUpdatablePropertiesEquals(DesignSession expected, DesignSession actual) {
        assertDesignSessionUpdatableFieldsEquals(expected, actual);
        assertDesignSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignSessionAutoGeneratedPropertiesEquals(DesignSession expected, DesignSession actual) {
        assertThat(actual)
            .as("Verify DesignSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignSessionUpdatableFieldsEquals(DesignSession expected, DesignSession actual) {
        assertThat(actual)
            .as("Verify DesignSession relevant properties")
            .satisfies(a -> assertThat(a.getSessionCode()).as("check sessionCode").isEqualTo(expected.getSessionCode()))
            .satisfies(a -> assertThat(a.getProjectType()).as("check projectType").isEqualTo(expected.getProjectType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getClientName()).as("check clientName").isEqualTo(expected.getClientName()))
            .satisfies(a -> assertThat(a.getClientEmail()).as("check clientEmail").isEqualTo(expected.getClientEmail()))
            .satisfies(a -> assertThat(a.getClientPhone()).as("check clientPhone").isEqualTo(expected.getClientPhone()))
            .satisfies(a -> assertThat(a.getSelectedStyle()).as("check selectedStyle").isEqualTo(expected.getSelectedStyle()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignSessionUpdatableRelationshipsEquals(DesignSession expected, DesignSession actual) {
        assertThat(actual)
            .as("Verify DesignSession relationships")
            .satisfies(a -> assertThat(a.getSpec()).as("check spec").isEqualTo(expected.getSpec()))
            .satisfies(a -> assertThat(a.getCatalogStyle()).as("check catalogStyle").isEqualTo(expected.getCatalogStyle()));
    }
}
