package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DesignArtifactAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignArtifactAllPropertiesEquals(DesignArtifact expected, DesignArtifact actual) {
        assertDesignArtifactAutoGeneratedPropertiesEquals(expected, actual);
        assertDesignArtifactAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignArtifactAllUpdatablePropertiesEquals(DesignArtifact expected, DesignArtifact actual) {
        assertDesignArtifactUpdatableFieldsEquals(expected, actual);
        assertDesignArtifactUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignArtifactAutoGeneratedPropertiesEquals(DesignArtifact expected, DesignArtifact actual) {
        assertThat(actual)
            .as("Verify DesignArtifact auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignArtifactUpdatableFieldsEquals(DesignArtifact expected, DesignArtifact actual) {
        assertThat(actual)
            .as("Verify DesignArtifact relevant properties")
            .satisfies(a -> assertThat(a.getArtifactType()).as("check artifactType").isEqualTo(expected.getArtifactType()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFilePath()).as("check filePath").isEqualTo(expected.getFilePath()))
            .satisfies(a -> assertThat(a.getMimeType()).as("check mimeType").isEqualTo(expected.getMimeType()))
            .satisfies(a -> assertThat(a.getFileSizeKb()).as("check fileSizeKb").isEqualTo(expected.getFileSizeKb()))
            .satisfies(a -> assertThat(a.getChecksum()).as("check checksum").isEqualTo(expected.getChecksum()))
            .satisfies(a -> assertThat(a.getMetadataJson()).as("check metadataJson").isEqualTo(expected.getMetadataJson()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignArtifactUpdatableRelationshipsEquals(DesignArtifact expected, DesignArtifact actual) {
        assertThat(actual)
            .as("Verify DesignArtifact relationships")
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
