package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DesignImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignImageAllPropertiesEquals(DesignImage expected, DesignImage actual) {
        assertDesignImageAutoGeneratedPropertiesEquals(expected, actual);
        assertDesignImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignImageAllUpdatablePropertiesEquals(DesignImage expected, DesignImage actual) {
        assertDesignImageUpdatableFieldsEquals(expected, actual);
        assertDesignImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignImageAutoGeneratedPropertiesEquals(DesignImage expected, DesignImage actual) {
        assertThat(actual)
            .as("Verify DesignImage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignImageUpdatableFieldsEquals(DesignImage expected, DesignImage actual) {
        assertThat(actual)
            .as("Verify DesignImage relevant properties")
            .satisfies(a -> assertThat(a.getImageType()).as("check imageType").isEqualTo(expected.getImageType()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFilePath()).as("check filePath").isEqualTo(expected.getFilePath()))
            .satisfies(a -> assertThat(a.getMimeType()).as("check mimeType").isEqualTo(expected.getMimeType()))
            .satisfies(a -> assertThat(a.getFileSizeKb()).as("check fileSizeKb").isEqualTo(expected.getFileSizeKb()))
            .satisfies(a -> assertThat(a.getWidthPx()).as("check widthPx").isEqualTo(expected.getWidthPx()))
            .satisfies(a -> assertThat(a.getHeightPx()).as("check heightPx").isEqualTo(expected.getHeightPx()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getUploadedAt()).as("check uploadedAt").isEqualTo(expected.getUploadedAt()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignImageUpdatableRelationshipsEquals(DesignImage expected, DesignImage actual) {
        assertThat(actual)
            .as("Verify DesignImage relationships")
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
