package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GenerationJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenerationJobAllPropertiesEquals(GenerationJob expected, GenerationJob actual) {
        assertGenerationJobAutoGeneratedPropertiesEquals(expected, actual);
        assertGenerationJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenerationJobAllUpdatablePropertiesEquals(GenerationJob expected, GenerationJob actual) {
        assertGenerationJobUpdatableFieldsEquals(expected, actual);
        assertGenerationJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenerationJobAutoGeneratedPropertiesEquals(GenerationJob expected, GenerationJob actual) {
        assertThat(actual)
            .as("Verify GenerationJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenerationJobUpdatableFieldsEquals(GenerationJob expected, GenerationJob actual) {
        assertThat(actual)
            .as("Verify GenerationJob relevant properties")
            .satisfies(a -> assertThat(a.getJobType()).as("check jobType").isEqualTo(expected.getJobType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getInputJson()).as("check inputJson").isEqualTo(expected.getInputJson()))
            .satisfies(a -> assertThat(a.getOutputJson()).as("check outputJson").isEqualTo(expected.getOutputJson()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGenerationJobUpdatableRelationshipsEquals(GenerationJob expected, GenerationJob actual) {
        assertThat(actual)
            .as("Verify GenerationJob relationships")
            .satisfies(a -> assertThat(a.getArtifact()).as("check artifact").isEqualTo(expected.getArtifact()))
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
