package com.kalitron.studio.domain;

import static com.kalitron.studio.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class HardwareAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareAllPropertiesEquals(Hardware expected, Hardware actual) {
        assertHardwareAutoGeneratedPropertiesEquals(expected, actual);
        assertHardwareAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareAllUpdatablePropertiesEquals(Hardware expected, Hardware actual) {
        assertHardwareUpdatableFieldsEquals(expected, actual);
        assertHardwareUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareAutoGeneratedPropertiesEquals(Hardware expected, Hardware actual) {
        assertThat(actual)
            .as("Verify Hardware auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareUpdatableFieldsEquals(Hardware expected, Hardware actual) {
        assertThat(actual)
            .as("Verify Hardware relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getHardwareType()).as("check hardwareType").isEqualTo(expected.getHardwareType()))
            .satisfies(a ->
                assertThat(a.getUnitCostMxn())
                    .as("check unitCostMxn")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getUnitCostMxn())
            )
            .satisfies(a -> assertThat(a.getSupplierName()).as("check supplierName").isEqualTo(expected.getSupplierName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareUpdatableRelationshipsEquals(Hardware expected, Hardware actual) {
        // empty method
    }
}
