package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KitchenSpecAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKitchenSpecAllPropertiesEquals(KitchenSpec expected, KitchenSpec actual) {
        assertKitchenSpecAutoGeneratedPropertiesEquals(expected, actual);
        assertKitchenSpecAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKitchenSpecAllUpdatablePropertiesEquals(KitchenSpec expected, KitchenSpec actual) {
        assertKitchenSpecUpdatableFieldsEquals(expected, actual);
        assertKitchenSpecUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKitchenSpecAutoGeneratedPropertiesEquals(KitchenSpec expected, KitchenSpec actual) {
        assertThat(actual)
            .as("Verify KitchenSpec auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKitchenSpecUpdatableFieldsEquals(KitchenSpec expected, KitchenSpec actual) {
        assertThat(actual)
            .as("Verify KitchenSpec relevant properties")
            .satisfies(a -> assertThat(a.getLayout()).as("check layout").isEqualTo(expected.getLayout()))
            .satisfies(a -> assertThat(a.getTotalWidthMm()).as("check totalWidthMm").isEqualTo(expected.getTotalWidthMm()))
            .satisfies(a -> assertThat(a.getTotalHeightMm()).as("check totalHeightMm").isEqualTo(expected.getTotalHeightMm()))
            .satisfies(a -> assertThat(a.getTotalDepthMm()).as("check totalDepthMm").isEqualTo(expected.getTotalDepthMm()))
            .satisfies(a -> assertThat(a.getStyle()).as("check style").isEqualTo(expected.getStyle()))
            .satisfies(a -> assertThat(a.getPrimaryFinish()).as("check primaryFinish").isEqualTo(expected.getPrimaryFinish()))
            .satisfies(a -> assertThat(a.getHandleType()).as("check handleType").isEqualTo(expected.getHandleType()))
            .satisfies(a ->
                assertThat(a.getCountertopMaterial()).as("check countertopMaterial").isEqualTo(expected.getCountertopMaterial())
            )
            .satisfies(a -> assertThat(a.getSinkPosition()).as("check sinkPosition").isEqualTo(expected.getSinkPosition()))
            .satisfies(a -> assertThat(a.getConfirmedByClient()).as("check confirmedByClient").isEqualTo(expected.getConfirmedByClient()))
            .satisfies(a -> assertThat(a.getExtractedJson()).as("check extractedJson").isEqualTo(expected.getExtractedJson()))
            .satisfies(a -> assertThat(a.getConfirmedAt()).as("check confirmedAt").isEqualTo(expected.getConfirmedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKitchenSpecUpdatableRelationshipsEquals(KitchenSpec expected, KitchenSpec actual) {
        assertThat(actual)
            .as("Verify KitchenSpec relationships")
            .satisfies(a -> assertThat(a.getPrimaryMaterial()).as("check primaryMaterial").isEqualTo(expected.getPrimaryMaterial()));
    }
}
