package com.kalitron.studio.domain;

import static com.kalitron.studio.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MaterialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialAllPropertiesEquals(Material expected, Material actual) {
        assertMaterialAutoGeneratedPropertiesEquals(expected, actual);
        assertMaterialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialAllUpdatablePropertiesEquals(Material expected, Material actual) {
        assertMaterialUpdatableFieldsEquals(expected, actual);
        assertMaterialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialAutoGeneratedPropertiesEquals(Material expected, Material actual) {
        assertThat(actual)
            .as("Verify Material auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialUpdatableFieldsEquals(Material expected, Material actual) {
        assertThat(actual)
            .as("Verify Material relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getMaterialKind()).as("check materialKind").isEqualTo(expected.getMaterialKind()))
            .satisfies(a -> assertThat(a.getThicknessMm()).as("check thicknessMm").isEqualTo(expected.getThicknessMm()))
            .satisfies(a -> assertThat(a.getSheetWidthMm()).as("check sheetWidthMm").isEqualTo(expected.getSheetWidthMm()))
            .satisfies(a -> assertThat(a.getSheetHeightMm()).as("check sheetHeightMm").isEqualTo(expected.getSheetHeightMm()))
            .satisfies(a ->
                assertThat(a.getCostPerSheetMxn())
                    .as("check costPerSheetMxn")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCostPerSheetMxn())
            )
            .satisfies(a ->
                assertThat(a.getCostPerSquareMeterMxn())
                    .as("check costPerSquareMeterMxn")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCostPerSquareMeterMxn())
            )
            .satisfies(a -> assertThat(a.getSupplierName()).as("check supplierName").isEqualTo(expected.getSupplierName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialUpdatableRelationshipsEquals(Material expected, Material actual) {
        // empty method
    }
}
