package com.kalitron.studio.domain;

import static com.kalitron.studio.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class QuoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteAllPropertiesEquals(Quote expected, Quote actual) {
        assertQuoteAutoGeneratedPropertiesEquals(expected, actual);
        assertQuoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteAllUpdatablePropertiesEquals(Quote expected, Quote actual) {
        assertQuoteUpdatableFieldsEquals(expected, actual);
        assertQuoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteAutoGeneratedPropertiesEquals(Quote expected, Quote actual) {
        assertThat(actual)
            .as("Verify Quote auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteUpdatableFieldsEquals(Quote expected, Quote actual) {
        assertThat(actual)
            .as("Verify Quote relevant properties")
            .satisfies(a -> assertThat(a.getQuoteNumber()).as("check quoteNumber").isEqualTo(expected.getQuoteNumber()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getSubtotalMxn())
                    .as("check subtotalMxn")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSubtotalMxn())
            )
            .satisfies(a ->
                assertThat(a.getTaxMxn()).as("check taxMxn").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxMxn())
            )
            .satisfies(a ->
                assertThat(a.getTotalMxn()).as("check totalMxn").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotalMxn())
            )
            .satisfies(a ->
                assertThat(a.getLaborMxn()).as("check laborMxn").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLaborMxn())
            )
            .satisfies(a -> assertThat(a.getValidUntil()).as("check validUntil").isEqualTo(expected.getValidUntil()))
            .satisfies(a -> assertThat(a.getPublicToken()).as("check publicToken").isEqualTo(expected.getPublicToken()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getSentAt()).as("check sentAt").isEqualTo(expected.getSentAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteUpdatableRelationshipsEquals(Quote expected, Quote actual) {
        assertThat(actual)
            .as("Verify Quote relationships")
            .satisfies(a -> assertThat(a.getRenderImage()).as("check renderImage").isEqualTo(expected.getRenderImage()))
            .satisfies(a -> assertThat(a.getPdfArtifact()).as("check pdfArtifact").isEqualTo(expected.getPdfArtifact()))
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
