package com.kalitron.studio.domain;

import static com.kalitron.studio.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class QuoteItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteItemAllPropertiesEquals(QuoteItem expected, QuoteItem actual) {
        assertQuoteItemAutoGeneratedPropertiesEquals(expected, actual);
        assertQuoteItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteItemAllUpdatablePropertiesEquals(QuoteItem expected, QuoteItem actual) {
        assertQuoteItemUpdatableFieldsEquals(expected, actual);
        assertQuoteItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteItemAutoGeneratedPropertiesEquals(QuoteItem expected, QuoteItem actual) {
        assertThat(actual)
            .as("Verify QuoteItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteItemUpdatableFieldsEquals(QuoteItem expected, QuoteItem actual) {
        assertThat(actual)
            .as("Verify QuoteItem relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getUnitPriceMxn())
                    .as("check unitPriceMxn")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getUnitPriceMxn())
            )
            .satisfies(a ->
                assertThat(a.getTotalMxn()).as("check totalMxn").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotalMxn())
            )
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuoteItemUpdatableRelationshipsEquals(QuoteItem expected, QuoteItem actual) {
        assertThat(actual)
            .as("Verify QuoteItem relationships")
            .satisfies(a -> assertThat(a.getCabinet()).as("check cabinet").isEqualTo(expected.getCabinet()))
            .satisfies(a -> assertThat(a.getHardware()).as("check hardware").isEqualTo(expected.getHardware()))
            .satisfies(a -> assertThat(a.getQuote()).as("check quote").isEqualTo(expected.getQuote()));
    }
}
