package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RoomWallAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomWallAllPropertiesEquals(RoomWall expected, RoomWall actual) {
        assertRoomWallAutoGeneratedPropertiesEquals(expected, actual);
        assertRoomWallAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomWallAllUpdatablePropertiesEquals(RoomWall expected, RoomWall actual) {
        assertRoomWallUpdatableFieldsEquals(expected, actual);
        assertRoomWallUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomWallAutoGeneratedPropertiesEquals(RoomWall expected, RoomWall actual) {
        assertThat(actual)
            .as("Verify RoomWall auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomWallUpdatableFieldsEquals(RoomWall expected, RoomWall actual) {
        assertThat(actual)
            .as("Verify RoomWall relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLengthMm()).as("check lengthMm").isEqualTo(expected.getLengthMm()))
            .satisfies(a -> assertThat(a.getHeightMm()).as("check heightMm").isEqualTo(expected.getHeightMm()))
            .satisfies(a -> assertThat(a.getAngleDeg()).as("check angleDeg").isEqualTo(expected.getAngleDeg()))
            .satisfies(a -> assertThat(a.getPositionX()).as("check positionX").isEqualTo(expected.getPositionX()))
            .satisfies(a -> assertThat(a.getPositionY()).as("check positionY").isEqualTo(expected.getPositionY()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomWallUpdatableRelationshipsEquals(RoomWall expected, RoomWall actual) {
        assertThat(actual)
            .as("Verify RoomWall relationships")
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
