package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RoomObstacleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomObstacleAllPropertiesEquals(RoomObstacle expected, RoomObstacle actual) {
        assertRoomObstacleAutoGeneratedPropertiesEquals(expected, actual);
        assertRoomObstacleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomObstacleAllUpdatablePropertiesEquals(RoomObstacle expected, RoomObstacle actual) {
        assertRoomObstacleUpdatableFieldsEquals(expected, actual);
        assertRoomObstacleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomObstacleAutoGeneratedPropertiesEquals(RoomObstacle expected, RoomObstacle actual) {
        assertThat(actual)
            .as("Verify RoomObstacle auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomObstacleUpdatableFieldsEquals(RoomObstacle expected, RoomObstacle actual) {
        assertThat(actual)
            .as("Verify RoomObstacle relevant properties")
            .satisfies(a -> assertThat(a.getObstacleType()).as("check obstacleType").isEqualTo(expected.getObstacleType()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getxMm()).as("check xMm").isEqualTo(expected.getxMm()))
            .satisfies(a -> assertThat(a.getyMm()).as("check yMm").isEqualTo(expected.getyMm()))
            .satisfies(a -> assertThat(a.getzMm()).as("check zMm").isEqualTo(expected.getzMm()))
            .satisfies(a -> assertThat(a.getWidthMm()).as("check widthMm").isEqualTo(expected.getWidthMm()))
            .satisfies(a -> assertThat(a.getHeightMm()).as("check heightMm").isEqualTo(expected.getHeightMm()))
            .satisfies(a -> assertThat(a.getDepthMm()).as("check depthMm").isEqualTo(expected.getDepthMm()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoomObstacleUpdatableRelationshipsEquals(RoomObstacle expected, RoomObstacle actual) {
        assertThat(actual)
            .as("Verify RoomObstacle relationships")
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
