package com.kalitron.studio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SiteMeasurementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteMeasurementAllPropertiesEquals(SiteMeasurement expected, SiteMeasurement actual) {
        assertSiteMeasurementAutoGeneratedPropertiesEquals(expected, actual);
        assertSiteMeasurementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteMeasurementAllUpdatablePropertiesEquals(SiteMeasurement expected, SiteMeasurement actual) {
        assertSiteMeasurementUpdatableFieldsEquals(expected, actual);
        assertSiteMeasurementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteMeasurementAutoGeneratedPropertiesEquals(SiteMeasurement expected, SiteMeasurement actual) {
        assertThat(actual)
            .as("Verify SiteMeasurement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteMeasurementUpdatableFieldsEquals(SiteMeasurement expected, SiteMeasurement actual) {
        assertThat(actual)
            .as("Verify SiteMeasurement relevant properties")
            .satisfies(a -> assertThat(a.getMeasurementUuid()).as("check measurementUuid").isEqualTo(expected.getMeasurementUuid()))
            .satisfies(a -> assertThat(a.getProjectType()).as("check projectType").isEqualTo(expected.getProjectType()))
            .satisfies(a -> assertThat(a.getRevision()).as("check revision").isEqualTo(expected.getRevision()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getSchemaVersion()).as("check schemaVersion").isEqualTo(expected.getSchemaVersion()))
            .satisfies(a -> assertThat(a.getCatalogVersion()).as("check catalogVersion").isEqualTo(expected.getCatalogVersion()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()))
            .satisfies(a -> assertThat(a.getPayloadSha256()).as("check payloadSha256").isEqualTo(expected.getPayloadSha256()))
            .satisfies(a -> assertThat(a.getFloorOutOfLevelMm()).as("check floorOutOfLevelMm").isEqualTo(expected.getFloorOutOfLevelMm()))
            .satisfies(a ->
                assertThat(a.getFloorOutOfLevelNote()).as("check floorOutOfLevelNote").isEqualTo(expected.getFloorOutOfLevelNote())
            )
            .satisfies(a -> assertThat(a.getDeviceId()).as("check deviceId").isEqualTo(expected.getDeviceId()))
            .satisfies(a -> assertThat(a.getAppVersion()).as("check appVersion").isEqualTo(expected.getAppVersion()))
            .satisfies(a -> assertThat(a.getLaserModel()).as("check laserModel").isEqualTo(expected.getLaserModel()))
            .satisfies(a -> assertThat(a.getCapturedAt()).as("check capturedAt").isEqualTo(expected.getCapturedAt()))
            .satisfies(a -> assertThat(a.getReceivedAt()).as("check receivedAt").isEqualTo(expected.getReceivedAt()))
            .satisfies(a -> assertThat(a.getConfirmedAt()).as("check confirmedAt").isEqualTo(expected.getConfirmedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSiteMeasurementUpdatableRelationshipsEquals(SiteMeasurement expected, SiteMeasurement actual) {
        assertThat(actual)
            .as("Verify SiteMeasurement relationships")
            .satisfies(a -> assertThat(a.getSession()).as("check session").isEqualTo(expected.getSession()));
    }
}
